server:
  port: 0

spring:
  profiles: docker
  sleuth:
    sampler:
      percentage: 1.0  zipkin:
    baseUrl: http://bruno-vbox.local:9411/zipkin/

eureka:
  instance:
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://192.168.1.148:8761/eureka/
