server:
  port: 0

eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://192.168.1.148:8761/eureka/

---
spring:
  profiles: docker
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://bruno-vbox.local:9411/zipkin/
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
      
      
  
