server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  debug:
    request: true
  routes:
    card-service:
        path: /card-service/**
        serviceId: card-service
        stripPrefix: true
    statement-service:
        path: /statement-service/**
        serviceId: statement-service
        stripPrefix: true
    card-statement-composite:
        path: /card-statement-composite/**
        serviceId: card-statement-composite
        stripPrefix: true
---
spring:
  profiles: docker
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://bruno-vbox.local:9411/zipkin/
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
