server:
  port: 0
turbine:
  amqp:
    port: 8989
  appConfig: card-service,statement-service,card-statement-composite,edge-server
  aggregator:
    clusterConfig: CLUSTER
  clusterNameExpression: metadata['cluster']
  combineHostPort: true 
    
turbine.stream.port: 8989

---
spring:
  profiles: docker
  rabbitmq:
    host: 192.168.1.100
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8989
